#!/bin/sh
cd /var/git/cgal.git/refs

# TODO use branch given by CDash build server
branch="$(wget -O- -q http://scm.cgal.org/CDash/todays_branch.txt)"
date="$(date +%Y-%m-%d)"

#if new commit from today exit
if [ -e nightly/$branch/$date ];
then
  cp nightly/$branch/$date testsuite/$branch
else
  # keep old version
fi

