#!/bin/bash

# TODO subgit uninstall

# TODO disable svn-write

# TODO remove www.cgal.org directory in cgal-web

# TODO right user

REPO=cgal-web

# create branches for hooks

git clone /var/git/$REPO.git /var/git/$REPO 

cd /var/git/$REPO

git remote add hooks ~/cgal-hooks
git fetch hooks

git checkout --orphan client-hooks
git rm -fr *
git commit -m "prepare to place client hooks" 
git merge -s ours --no-commit hooks/master
git read-tree --prefix=/ -u hooks/master:client-hooks
git commit -m "placed client hooks"
git push origin client-hooks

git checkout --orphan server-hooks
git rm -fr *
git commit -m "prepare to place server hooks" 
git merge -s ours --no-commit hooks/master
git read-tree --prefix=/ -u hooks/master:server-hooks
git commit -m "placed server hooks"
git push origin server-hooks

# install server hooks

cd /var/git/$REPO.git/hooks
git init 
git pull .. server-hooks

# rm -fr /var/git/$REPO

# TODO email list
echo >> /var/git/$REPO.git/config <<EOF
[hooks]
        mailinglist = "eric@mpi-inf.mpg.de"
        senderemail = "git@scm.cgal.org"
        emailprefix = "[cgal.git]"
        showrev = "git show -C %s; echo" 
EOF
