#!/bin/bash

REPO=$1

# create branches for hooks

git clone /var/git/$REPO.git /var/git/$REPO 

cd /var/git/$REPO

git remote add hooks ~/cgal-hooks
git fetch hooks

HC=hooks-for-clients
git checkout --orphan $HC 
git rm -fr *
git commit -m "prepare to place client hooks" 
git merge -s ours --no-commit hooks/master
git read-tree --prefix=/ -u hooks/master:client-hooks
git commit -m "placed client hooks"
git push origin $HC 

HS=hooks-on-server
git checkout --orphan $HS 
git rm -fr *
git commit -m "prepare to place server hooks" 
git merge -s ours --no-commit hooks/master
git read-tree --prefix=/ -u hooks/master:server-hooks
git commit -m "placed server hooks"
git push origin $HS 

# install server hooks

cd /var/git/$REPO.git/hooks
git init 
git pull .. $HS 

# TODO email list
echo >> /var/git/$REPO.git/config <<EOF
[hooks]
        mailinglist = "eric@mpi-inf.mpg.de"
        senderemail = "git@scm.cgal.org"
        emailprefix = "[cgal.git]"
        showrev = "git show -C %s; echo" 
EOF

#delete temporary repo
rm -fr /var/git/$REPO
