#!/bin/bash
# taken from: http://public.kitware.com/Wiki/CDash:Design#Nightly_Revisions
# hooks/post-receive
while read oldrev newrev refname; do
  if echo $refname | grep "^refs/heads/" >/dev/null 2>&1; then
    branch="$(echo $refname | sed 's/^refs\/heads\///')"
    date="$(date +%Y-%m-%d)" # fix to account for nightly start time
    git update-ref -m "New commit published on this date" \
      "refs/nightly/$branch/$date" "$newrev"
  fi
done
