#!/bin/bash

# --- Command line
refname="$1"
oldrev="$2"
newrev="$3"

# Special rights for a set of trusted people.
case "$GIT_USER" in
    (lrineau|sloriot|eric) exit 0;;
esac

# If the branch is not master, allow
if [ "$refname" != refs/heads/master ]; then exit 0; fi

if [ `basename "${PWD}"` = "cgal-gsoc" ]; then
    if [ -z "$IN_CGAL_POST_UPDATE_PUSH_TO_GSOC" ]; then
        echo "ERROR:"
        echo "  You cannot push to master in the cgal-gsoc repository."
        echo "  Ask for more information on the CGAL developers mailing"
        echo "  list."
        echo ""
        exit 1
    fi
fi

# Forbid non-fast-forward updates to master
if ! [ "$(git merge-base "$oldrev" "$newrev")" = "$oldrev" ]; then
    echo ""
    echo "ERROR:"
    echo "  You cannot push a non fast-forward update to master in CGAL"
    echo "  git repositories!"
    echo "  Ask for help on the CGAL developers mailing list to solve"
    echo "  that issue."
    echo ""
    exit 1
fi

# Accept minor fixes
if git show "$newrev" | grep -iq 'minor fix.*master'; then
    if [ $(git log --oneline "$oldrev..$newrev" | wc -l) = 1 ]; then
        exit 0
    fi
fi

# Accept pushes that are said to be approved by the RM
if git show "$newrev" | grep -iEq 'App?rou?ved by the (RM|Release Manager)'; then
    exit 0
fi

# Accept modifications to Maintenance, Documentation, and */doc
if ! git diff-tree -r --raw "$oldrev" "$newrev" | grep -vE ' (Maintenance/|Documentation/|[^/]+/doc/|Installation/changes.html)'; then
    exit 0
fi

echo ""
echo "ERROR:"
echo "  You are not allowed to push the revision"
echo "  $newrev to master."
echo "  Ask for help on the CGAL developers mailing lists to solve"
echo "   that issue."
echo ""
exit 1
