#ifndef CGAL_LEVEL_OF_DETAIL_VISIBILITY_H
#define CGAL_LEVEL_OF_DETAIL_VISIBILITY_H

#include <CGAL/Visibility/Classification_based_visibility/Level_of_detail_classification_visibility_2.h>

#include <CGAL/Visibility/Classification_based_visibility/Strategies/Level_of_detail_classification_barycentre_visibility_strategy_2.h>
#include <CGAL/Visibility/Classification_based_visibility/Strategies/Level_of_detail_classification_naive_visibility_strategy_2.h>
#include <CGAL/Visibility/Classification_based_visibility/Strategies/Level_of_detail_classification_natural_neighbours_visibility_strategy_2.h>
#include <CGAL/Visibility/Classification_based_visibility/Strategies/Level_of_detail_classification_shepard_visibility_strategy_2.h>

#endif // CGAL_LEVEL_OF_DETAIL_VISIBILITY_H