#ifndef CGAL_LEVEL_OF_DETAIL_PARTITIONING_INCLUDE_H
#define CGAL_LEVEL_OF_DETAIL_PARTITIONING_INCLUDE_H

#include <CGAL/Level_of_detail/Partitioning/Kinetic_partitioning/Kinetic_based_partitioning_2.h>

#endif // CGAL_LEVEL_OF_DETAIL_PARTITIONING_INCLUDE_H