#!/bin/bash

./exp-make `cat data/akobel/*.cfg`

for set in `ls data/akobel/*.dat`; do
  echo "SET $set"
  for dir in `cat $set`; do
    echo $dir
    ./exp-run $(cat ${set%.dat}.cfg) data/akobel/$dir 1 300 
  done
done

