#ifndef CGAL_LEVEL_OF_DETAIL_SHAPE_DETECTION_INCLUDE_H
#define CGAL_LEVEL_OF_DETAIL_SHAPE_DETECTION_INCLUDE_H

#include <CGAL/Level_of_detail/Shape_detection/Region_growing/Region_growing_include.h>

#endif // CGAL_LEVEL_OF_DETAIL_SHAPE_DETECTION_INCLUDE_H